extern crate libc;
use libc::{
    PTRACE_CONT,
    PTRACE_KILL,
    CLONE_PTRACE,
    PTRACE_SEIZE,
    PTRACE_ATTACH,
    PTRACE_DETACH,
    PTRACE_LISTEN,
    PTRACE_GETREGS,
    PTRACE_SETREGS,
    PTRACE_SYSCALL,
    PTRACE_TRACEME,
    PTRACE_PEEKDATA,
    PTRACE_PEEKTEXT,
    PTRACE_PEEKUSER,
    PTRACE_POKEDATA,
    PTRACE_POKETEXT,
    PTRACE_POKEUSER,
    PTRACE_GETFPREGS,
    PTRACE_INTERRUPT,
    PTRACE_SETFPREGS,
    PTRACE_SETREGSET,
    PTRACE_GETFPXREGS,
    PTRACE_SETOPTIONS,
    PTRACE_SETSIGINFO,
    PTRACE_SINGLESTEP,
    PTRACE_GETEVENTMSG,
    PTRACE_PEEKSIGINFO,
    ptrace
};
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
    }
}
